keys:
  - &bismuth age1ud2k34l40xe39sw3vwcx7jhl092vyedsu7fg8l6l2v0pfvtqvegs794y9s
  - &helium age1f2dxwhdnduy8zqgq9t78xewln3fmjsv6vvxf3tahrlzuyz4l7ezsdjdhq8
  - &nickel age1uu5qyg046myhfh2makg6ycyrf6aqypjemke90et3l89z2uaegycsgakp98
  - &tungsten age1c6hrs6hhjnn8l6we48f6lea38cetnjzrdvjytcqztqqcaglvfvvq9ztja0

creation_rules:
  - path_regex: ^inputs/.*$
    key_groups:
      - age:
          - *bismuth
          - *helium
          - *nickel
          - *tungsten
